services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports: ['2181:2181']

    kafka:
        image: confluentinc/cp-kafka:7.6.1
        depends_on: [zookeeper]
        ports: ['9092:9092']
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: dwh
            MYSQL_USER: deuser
            MYSQL_PASSWORD: depass
        ports: ['3306:3306']
        command: ['--default-authentication-plugin=mysql_native_password']
